import '../models/campaign_stage.dart';

class CampaignDefaults {
  static const String mainCampaignId = 'main_campaign';

  static List<CampaignStage> stages({
    String campaignId = mainCampaignId,
  }) {
    return <CampaignStage>[
      _stage(
        campaignId: campaignId,
        order: 1,
        title: 'البداية',
        subtitle: 'غابة البداية - أجب عن 10 أسئلة وتعلم نظام النجوم.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['0'],
      ),
      _stage(
        campaignId: campaignId,
        order: 2,
        title: 'أول خطوة',
        subtitle: 'غابة البداية - أسئلة سهلة مع انتقال بسيط في المستوى.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['0'],
      ),
      _stage(
        campaignId: campaignId,
        order: 3,
        title: 'ثقة المعرفة',
        subtitle: 'غابة البداية - أثبت ثباتك في أسئلة المستوى الأول.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['0'],
      ),
      _stage(
        campaignId: campaignId,
        order: 4,
        title: 'سباق خفيف',
        subtitle: 'غابة البداية - أنه الأسئلة قبل انتهاء الوقت.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['0'],
        timeLimitSeconds: 150,
      ),
      _stage(
        campaignId: campaignId,
        order: 5,
        title: 'اختبار التركيز',
        subtitle: 'غابة البداية - لا تدع الأخطاء تصل إلى حد الإقصاء.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['0', '1'],
        maxWrongAnswers: 2,
      ),
      _stage(
        campaignId: campaignId,
        order: 6,
        title: 'بلا مساعدة',
        subtitle: 'غابة البداية - أكمل المرحلة دون أي وسيلة مساعدة.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['0', '1'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
      ),
      _stage(
        campaignId: campaignId,
        order: 7,
        title: 'النجاة الأولى',
        subtitle: 'غابة البداية - لديك ثلاث أرواح حتى نهاية المرحلة.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['0', '1'],
        lives: 3,
      ),
      _stage(
        campaignId: campaignId,
        order: 8,
        title: 'منافس مبتدئ',
        subtitle: 'غابة البداية - اهزم سامي في مواجهة ودية.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['1'],
        opponentName: 'سامي',
        opponentAccuracy: 55,
      ),
      _stage(
        campaignId: campaignId,
        order: 9,
        title: 'طريق الزعيم',
        subtitle: 'غابة البداية - سباق أسرع قبل أول مواجهة كبرى.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['1'],
        timeLimitSeconds: 120,
      ),
      _stage(
        campaignId: campaignId,
        order: 10,
        title: 'طارق السريع',
        subtitle: 'غابة البداية - اهزم الزعيم لفتح العالم التالي.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['1'],
        bossBotName: 'طارق السريع',
        bossBotIntelligence: 65,
      ),
      _stage(
        campaignId: campaignId,
        order: 11,
        title: 'بوابة التحدي',
        subtitle: 'تلال المعرفة - بداية متوسطة بأسئلة أكثر جدية.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['1', '2'],
      ),
      _stage(
        campaignId: campaignId,
        order: 12,
        title: 'ضغط الوقت',
        subtitle: 'تلال المعرفة - الوقت أقل والقرار أسرع.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['1', '2'],
        timeLimitSeconds: 100,
      ),
      _stage(
        campaignId: campaignId,
        order: 13,
        title: 'لا مجال للخطأ',
        subtitle: 'تلال المعرفة - خطأ واحد يكفي لإقصائك.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['1', '2'],
        maxWrongAnswers: 1,
      ),
      _stage(
        campaignId: campaignId,
        order: 14,
        title: 'نجاة المحترفين',
        subtitle: 'تلال المعرفة - حافظ على أرواحك أمام أسئلة أصعب.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['1', '2'],
        lives: 3,
      ),
      _stage(
        campaignId: campaignId,
        order: 15,
        title: 'منافسة النقاط',
        subtitle: 'تلال المعرفة - واجه مازن وتفوق عليه بالنقاط.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['2'],
        opponentName: 'مازن',
        opponentAccuracy: 65,
      ),
      _stage(
        campaignId: campaignId,
        order: 16,
        title: 'بدون جمهور',
        subtitle: 'تلال المعرفة - الجمهور والاتصال غير متاحين.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2'],
        allow5050: true,
        allowAudience: false,
        allowCall: false,
      ),
      _stage(
        campaignId: campaignId,
        order: 17,
        title: 'جولة فاصلة',
        subtitle: 'تلال المعرفة - اربح جولتين من ثلاث أمام رامي.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['2'],
        seriesRounds: 3,
        seriesWinsRequired: 2,
        opponentName: 'رامي',
        opponentAccuracy: 66,
      ),
      _stage(
        campaignId: campaignId,
        order: 18,
        title: 'مطاردة المنافس',
        subtitle: 'تلال المعرفة - تجاوز نتيجة الهدف قبل نهاية المرحلة.',
        campaignMode: CampaignMode.rival,
        winCondition: CampaignWinCondition.beatTargetScore,
        allowedLevels: const <String>['2'],
        targetScore: 700,
      ),
      _stage(
        campaignId: campaignId,
        order: 19,
        title: 'قبل البوابة',
        subtitle: 'تلال المعرفة - سباق ضيق مع مساعدات محدودة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['2', '4'],
        timeLimitSeconds: 90,
        allow5050: true,
        allowAudience: false,
        allowCall: false,
      ),
      _stage(
        campaignId: campaignId,
        order: 20,
        title: 'ليلى العبقرية',
        subtitle: 'تلال المعرفة - اهزم ليلى لفتح طريق المليون.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['2', '4'],
        bossBotName: 'ليلى العبقرية',
        bossBotIntelligence: 74,
      ),
      _stage(
        campaignId: campaignId,
        order: 21,
        title: 'أسئلة الكبار',
        subtitle: 'طريق المليون - مستوى صعب يحتاج تركيزا عاليا.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2', '4'],
      ),
      _stage(
        campaignId: campaignId,
        order: 22,
        title: 'ثلاث أرواح فقط',
        subtitle: 'طريق المليون - ثلاث فرص فقط حتى النهاية.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['2', '4'],
        lives: 3,
      ),
      _stage(
        campaignId: campaignId,
        order: 23,
        title: 'سباق المئة ثانية',
        subtitle: 'طريق المليون - مئة ثانية لعشر إجابات.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['2', '4'],
        timeLimitSeconds: 100,
      ),
      _stage(
        campaignId: campaignId,
        order: 24,
        title: 'إقصاء النخبة',
        subtitle: 'طريق المليون - خطأ واحد في أسئلة النخبة خطر حقيقي.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['2', '4'],
        maxWrongAnswers: 1,
      ),
      _stage(
        campaignId: campaignId,
        order: 25,
        title: 'سلسلة العباقرة',
        subtitle: 'طريق المليون - اربح سلسلة صعبة أمام نديم.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['2', '4'],
        seriesRounds: 3,
        seriesWinsRequired: 2,
        opponentName: 'نديم',
        opponentAccuracy: 72,
      ),
      _stage(
        campaignId: campaignId,
        order: 26,
        title: 'فريق المليون',
        subtitle: 'طريق المليون - تعاون مع سارة ضد فريق التحدي.',
        campaignMode: CampaignMode.teamBattle,
        winCondition: CampaignWinCondition.teamScore,
        allowedLevels: const <String>['2', '4'],
        teamAllyName: 'سارة',
        teamEnemyName: 'فريق التحدي',
        opponentAccuracy: 72,
      ),
      _stage(
        campaignId: campaignId,
        order: 27,
        title: 'ضد الزمن',
        subtitle: 'طريق المليون - 75 ثانية فقط أمام أسئلة عالية الصعوبة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['2', '4'],
        timeLimitSeconds: 75,
      ),
      _stage(
        campaignId: campaignId,
        order: 28,
        title: 'بلا طوق نجاة',
        subtitle: 'طريق المليون - لا توجد أي وسيلة مساعدة.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2', '4'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
      ),
      _stage(
        campaignId: campaignId,
        order: 29,
        title: 'قبل المليون',
        subtitle: 'طريق المليون - اهزم الخصم الذهبي قبل المواجهة الأخيرة.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['2', '4'],
        opponentName: 'الخصم الذهبي',
        opponentAccuracy: 76,
      ),
      _stage(
        campaignId: campaignId,
        order: 30,
        title: 'سيد المليون',
        subtitle: 'طريق المليون - المواجهة الأخيرة على قمة التحدي.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['2', '4'],
        timeLimitSeconds: 180,
        bossBotName: 'سيد المليون',
        bossBotIntelligence: 82,
      ),
      _stage(
        campaignId: campaignId,
        order: 31,
        title: 'بداية الصحراء',
        subtitle: 'صحراء الذكاء - بداية متقدمة بعد قمة التحدي.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2', '5'],
        unlockRequirementStars: 55,
        rewardCoins: 900,
        rewardGems: 7,
        rewardXp: 450,
      ),
      _stage(
        campaignId: campaignId,
        order: 32,
        title: 'سؤال تحت الضغط',
        subtitle: 'صحراء الذكاء - أجب بسرعة قبل أن ينتهي الوقت.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['2', '5'],
        timeLimitSeconds: 95,
        unlockRequirementStars: 57,
        rewardCoins: 970,
        rewardGems: 7,
        rewardXp: 480,
      ),
      _stage(
        campaignId: campaignId,
        order: 33,
        title: 'حياتان فقط',
        subtitle: 'صحراء الذكاء - فرصتان فقط للبقاء حتى النهاية.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['2', '5'],
        lives: 2,
        unlockRequirementStars: 59,
        rewardCoins: 1040,
        rewardGems: 8,
        rewardXp: 520,
      ),
      _stage(
        campaignId: campaignId,
        order: 34,
        title: 'بدون اتصال',
        subtitle: 'صحراء الذكاء - الهاتف غير متاح في هذه المرحلة.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2', '5'],
        allow5050: true,
        allowAudience: true,
        allowCall: false,
        unlockRequirementStars: 61,
        rewardCoins: 1110,
        rewardGems: 8,
        rewardXp: 550,
      ),
      _stage(
        campaignId: campaignId,
        order: 35,
        title: 'خصم الصحراء',
        subtitle: 'صحراء الذكاء - تفوق على زياد في مواجهة قوية.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['2', '5'],
        opponentName: 'زياد',
        opponentAccuracy: 78,
        unlockRequirementStars: 63,
        rewardCoins: 1180,
        rewardGems: 9,
        rewardXp: 590,
      ),
      _stage(
        campaignId: campaignId,
        order: 36,
        title: 'خطأ ممنوع',
        subtitle: 'صحراء الذكاء - خطأ واحد يكفي للإقصاء.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['2', '5'],
        maxWrongAnswers: 1,
        unlockRequirementStars: 65,
        rewardCoins: 1250,
        rewardGems: 9,
        rewardXp: 620,
      ),
      _stage(
        campaignId: campaignId,
        order: 37,
        title: 'سلسلة الصمود',
        subtitle: 'صحراء الذكاء - اربح جولتين من ثلاث أمام راكان.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['2', '5'],
        seriesRounds: 3,
        seriesWinsRequired: 2,
        opponentName: 'راكان',
        opponentAccuracy: 76,
        unlockRequirementStars: 67,
        rewardCoins: 1320,
        rewardGems: 10,
        rewardXp: 650,
      ),
      _stage(
        campaignId: campaignId,
        order: 38,
        title: 'مطاردة النقاط',
        subtitle: 'صحراء الذكاء - اجمع 800 نقطة قبل نهاية المرحلة.',
        campaignMode: CampaignMode.rival,
        winCondition: CampaignWinCondition.beatTargetScore,
        allowedLevels: const <String>['2', '5'],
        targetScore: 800,
        unlockRequirementStars: 68,
        rewardCoins: 1400,
        rewardGems: 10,
        rewardXp: 680,
      ),
      _stage(
        campaignId: campaignId,
        order: 39,
        title: 'عاصفة الوقت',
        subtitle: 'صحراء الذكاء - وقت أقل ومساعدات محدودة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['4', '5'],
        timeLimitSeconds: 80,
        allow5050: true,
        allowAudience: false,
        allowCall: false,
        unlockRequirementStars: 69,
        rewardCoins: 1500,
        rewardGems: 11,
        rewardXp: 700,
      ),
      _stage(
        campaignId: campaignId,
        order: 40,
        title: 'حارس الصحراء',
        subtitle: 'صحراء الذكاء - اهزم حارس الصحراء لفتح المدينة.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['5'],
        bossBotName: 'حارس الصحراء',
        bossBotIntelligence: 80,
        unlockRequirementStars: 70,
        rewardCoins: 1800,
        rewardGems: 14,
        rewardXp: 850,
      ),
      _stage(
        campaignId: campaignId,
        order: 41,
        title: 'بوابة المدينة',
        subtitle: 'مدينة العباقرة - بداية عالم المنافسين المتقدمين.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2', '6'],
        unlockRequirementStars: 72,
        rewardCoins: 1400,
        rewardGems: 10,
        rewardXp: 650,
      ),
      _stage(
        campaignId: campaignId,
        order: 42,
        title: 'سباق المدينة',
        subtitle: 'مدينة العباقرة - سباق سريع أمام أسئلة أصعب.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['2', '6'],
        timeLimitSeconds: 85,
        unlockRequirementStars: 74,
        rewardCoins: 1500,
        rewardGems: 11,
        rewardXp: 690,
      ),
      _stage(
        campaignId: campaignId,
        order: 43,
        title: 'منافس ذكي',
        subtitle: 'مدينة العباقرة - واجه حازم وتفوق عليه بالنقاط.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['2', '6'],
        opponentName: 'حازم',
        opponentAccuracy: 80,
        unlockRequirementStars: 76,
        rewardCoins: 1600,
        rewardGems: 12,
        rewardXp: 730,
      ),
      _stage(
        campaignId: campaignId,
        order: 44,
        title: 'بدون جمهور ولا اتصال',
        subtitle: 'مدينة العباقرة - الجمهور والاتصال غير متاحين.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['2', '6'],
        allow5050: true,
        allowAudience: false,
        allowCall: false,
        unlockRequirementStars: 78,
        rewardCoins: 1700,
        rewardGems: 12,
        rewardXp: 780,
      ),
      _stage(
        campaignId: campaignId,
        order: 45,
        title: 'نجاة المدينة',
        subtitle: 'مدينة العباقرة - حافظ على الأرواح أمام ضغط المدينة.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['2', '6'],
        lives: 3,
        unlockRequirementStars: 80,
        rewardCoins: 1800,
        rewardGems: 13,
        rewardXp: 830,
      ),
      _stage(
        campaignId: campaignId,
        order: 46,
        title: 'إقصاء سريع',
        subtitle: 'مدينة العباقرة - خطأ واحد قد ينهي المرحلة.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['2', '6'],
        maxWrongAnswers: 1,
        unlockRequirementStars: 82,
        rewardCoins: 1900,
        rewardGems: 14,
        rewardXp: 880,
      ),
      _stage(
        campaignId: campaignId,
        order: 47,
        title: 'فريق ضد فريق',
        subtitle: 'مدينة العباقرة - تعاون مع سارة ضد فريق التحدي.',
        campaignMode: CampaignMode.teamBattle,
        winCondition: CampaignWinCondition.teamScore,
        allowedLevels: const <String>['2', '6'],
        teamAllyName: 'سارة',
        teamEnemyName: 'فريق التحدي',
        opponentAccuracy: 78,
        unlockRequirementStars: 84,
        rewardCoins: 2000,
        rewardGems: 14,
        rewardXp: 920,
      ),
      _stage(
        campaignId: campaignId,
        order: 48,
        title: 'مطاردة العبقري',
        subtitle: 'مدينة العباقرة - تغلب على العبقري في مواجهة مباشرة.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['2', '6'],
        opponentName: 'العبقري',
        opponentAccuracy: 82,
        unlockRequirementStars: 86,
        rewardCoins: 2100,
        rewardGems: 15,
        rewardXp: 960,
      ),
      _stage(
        campaignId: campaignId,
        order: 49,
        title: 'قبل الزعيم',
        subtitle: 'مدينة العباقرة - سباق أخير قبل مواجهة الزعيم.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['6'],
        timeLimitSeconds: 70,
        allow5050: true,
        allowAudience: false,
        allowCall: false,
        unlockRequirementStars: 88,
        rewardCoins: 2200,
        rewardGems: 16,
        rewardXp: 1000,
      ),
      _stage(
        campaignId: campaignId,
        order: 50,
        title: 'نادر الحكيم',
        subtitle: 'مدينة العباقرة - المواجهة الكبرى مع نادر الحكيم.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['6'],
        bossBotName: 'نادر الحكيم',
        bossBotIntelligence: 84,
        unlockRequirementStars: 90,
        rewardCoins: 3000,
        rewardGems: 22,
        rewardXp: 1400,
      ),
      _stage(
        campaignId: campaignId,
        order: 51,
        title: 'صعود الجبل',
        subtitle: 'جبل الأسئلة - بداية صعود جديد نحو قمة أصعب.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['4', '5'],
        rewardCoins: 2200,
        rewardGems: 16,
        rewardXp: 1000,
      ),
      _stage(
        campaignId: campaignId,
        order: 52,
        title: 'نفس طويل',
        subtitle: 'جبل الأسئلة - اصمد بثلاث أرواح حتى نهاية الصعود.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['4', '5'],
        lives: 3,
        rewardCoins: 2325,
        rewardGems: 17,
        rewardXp: 1060,
      ),
      _stage(
        campaignId: campaignId,
        order: 53,
        title: 'قمة السرعة',
        subtitle: 'جبل الأسئلة - أسرع قبل أن ينتهي وقت القمة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['4', '5'],
        timeLimitSeconds: 85,
        rewardCoins: 2450,
        rewardGems: 18,
        rewardXp: 1120,
      ),
      _stage(
        campaignId: campaignId,
        order: 54,
        title: 'بلا مساعدات',
        subtitle: 'جبل الأسئلة - لا وسائل مساعدة في هذا المسار.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['4', '5'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 2575,
        rewardGems: 19,
        rewardXp: 1180,
      ),
      _stage(
        campaignId: campaignId,
        order: 55,
        title: 'تحدي القمة',
        subtitle: 'جبل الأسئلة - اهزم فارس القمة بالنقاط.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['4', '5'],
        opponentName: 'فارس القمة',
        opponentAccuracy: 80,
        rewardCoins: 2700,
        rewardGems: 20,
        rewardXp: 1240,
      ),
      _stage(
        campaignId: campaignId,
        order: 56,
        title: 'إقصاء الجبل',
        subtitle: 'جبل الأسئلة - خطأ واحد يكفي للسقوط.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['4', '5'],
        maxWrongAnswers: 1,
        rewardCoins: 2825,
        rewardGems: 21,
        rewardXp: 1300,
      ),
      _stage(
        campaignId: campaignId,
        order: 57,
        title: 'سلسلة القمة',
        subtitle: 'جبل الأسئلة - اربح السلسلة أمام راشد.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['5', '6'],
        seriesRounds: 3,
        seriesWinsRequired: 2,
        opponentName: 'راشد',
        opponentAccuracy: 80,
        rewardCoins: 2950,
        rewardGems: 22,
        rewardXp: 1360,
      ),
      _stage(
        campaignId: campaignId,
        order: 58,
        title: 'فريق الجبل',
        subtitle: 'جبل الأسئلة - تعاون مع ليان ضد فريق القمة.',
        campaignMode: CampaignMode.teamBattle,
        winCondition: CampaignWinCondition.teamScore,
        allowedLevels: const <String>['6'],
        teamAllyName: 'ليان',
        teamEnemyName: 'فريق القمة',
        opponentAccuracy: 80,
        rewardCoins: 3075,
        rewardGems: 23,
        rewardXp: 1430,
      ),
      _stage(
        campaignId: campaignId,
        order: 59,
        title: 'آخر صعود',
        subtitle: 'جبل الأسئلة - سبعون ثانية ومساعدات محدودة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['6', '7'],
        timeLimitSeconds: 70,
        allow5050: true,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 3200,
        rewardGems: 24,
        rewardXp: 1500,
      ),
      _stage(
        campaignId: campaignId,
        order: 60,
        title: 'حارس القمة',
        subtitle: 'جبل الأسئلة - اهزم حارس القمة لعبور الجبل.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['6', '7'],
        bossBotName: 'حارس القمة',
        bossBotIntelligence: 85,
        rewardCoins: 4000,
        rewardGems: 30,
        rewardXp: 1800,
      ),
      _stage(
        campaignId: campaignId,
        order: 61,
        title: 'موجة سهلة',
        subtitle: 'بحر المعرفة - بداية هادئة قبل التيار السريع.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['6'],
        rewardCoins: 3000,
        rewardGems: 22,
        rewardXp: 1400,
      ),
      _stage(
        campaignId: campaignId,
        order: 62,
        title: 'تيار سريع',
        subtitle: 'بحر المعرفة - أنه الأسئلة مع تيار الوقت.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['6', '7'],
        timeLimitSeconds: 80,
        rewardCoins: 3180,
        rewardGems: 24,
        rewardXp: 1500,
      ),
      _stage(
        campaignId: campaignId,
        order: 63,
        title: 'ثلاث فرص',
        subtitle: 'بحر المعرفة - ثلاث أرواح أمام ضغط الموج.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['6', '7'],
        lives: 3,
        rewardCoins: 3360,
        rewardGems: 25,
        rewardXp: 1600,
      ),
      _stage(
        campaignId: campaignId,
        order: 64,
        title: 'بلا طوق نجاة',
        subtitle: 'بحر المعرفة - لا مساعدات في اختبار العمق.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['6', '7'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 3540,
        rewardGems: 27,
        rewardXp: 1700,
      ),
      _stage(
        campaignId: campaignId,
        order: 65,
        title: 'منافس البحر',
        subtitle: 'بحر المعرفة - واجه مروان في منافسة سريعة.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['6', '7'],
        opponentName: 'مروان',
        opponentAccuracy: 82,
        rewardCoins: 3720,
        rewardGems: 28,
        rewardXp: 1800,
      ),
      _stage(
        campaignId: campaignId,
        order: 66,
        title: 'موجة الإقصاء',
        subtitle: 'بحر المعرفة - لا مجال للخطأ وسط الموج.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['6', '7'],
        maxWrongAnswers: 1,
        rewardCoins: 3900,
        rewardGems: 30,
        rewardXp: 1900,
      ),
      _stage(
        campaignId: campaignId,
        order: 67,
        title: 'مطاردة الموج',
        subtitle: 'بحر المعرفة - اجمع 850 نقطة قبل نهاية المرحلة.',
        campaignMode: CampaignMode.rival,
        winCondition: CampaignWinCondition.beatTargetScore,
        allowedLevels: const <String>['7'],
        targetScore: 850,
        rewardCoins: 4080,
        rewardGems: 31,
        rewardXp: 2000,
      ),
      _stage(
        campaignId: campaignId,
        order: 68,
        title: 'عاصفة البحر',
        subtitle: 'بحر المعرفة - عاصفة سرعة بستين وخمس ثوان.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['7'],
        timeLimitSeconds: 65,
        rewardCoins: 4260,
        rewardGems: 33,
        rewardXp: 2100,
      ),
      _stage(
        campaignId: campaignId,
        order: 69,
        title: 'اختبار الأعماق',
        subtitle: 'بحر المعرفة - حياتان فقط في الأعماق.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['7'],
        lives: 2,
        rewardCoins: 4500,
        rewardGems: 34,
        rewardXp: 2200,
      ),
      _stage(
        campaignId: campaignId,
        order: 70,
        title: 'زعيم الأعماق',
        subtitle: 'بحر المعرفة - اهزم زعيم الأعماق.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['7'],
        bossBotName: 'زعيم الأعماق',
        bossBotIntelligence: 86,
        rewardCoins: 5500,
        rewardGems: 40,
        rewardXp: 2600,
      ),
      _stage(
        campaignId: campaignId,
        order: 71,
        title: 'بداية المختبر',
        subtitle: 'مختبر العباقرة - بداية تجارب الضغط العلمي.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['7'],
        rewardCoins: 4500,
        rewardGems: 32,
        rewardXp: 2200,
      ),
      _stage(
        campaignId: campaignId,
        order: 72,
        title: 'تجربة الوقت',
        subtitle: 'مختبر العباقرة - الوقت جزء من التجربة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['7'],
        timeLimitSeconds: 75,
        rewardCoins: 4750,
        rewardGems: 34,
        rewardXp: 2325,
      ),
      _stage(
        campaignId: campaignId,
        order: 73,
        title: 'تجربة بلا مساعدات',
        subtitle: 'مختبر العباقرة - اختبر معرفتك دون أي أداة.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['7', '8'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 5000,
        rewardGems: 36,
        rewardXp: 2450,
      ),
      _stage(
        campaignId: campaignId,
        order: 74,
        title: 'تجربة الإقصاء',
        subtitle: 'مختبر العباقرة - خطأ واحد يفسد التجربة.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['8'],
        maxWrongAnswers: 1,
        rewardCoins: 5250,
        rewardGems: 38,
        rewardXp: 2575,
      ),
      _stage(
        campaignId: campaignId,
        order: 75,
        title: 'تجربة النجاة',
        subtitle: 'مختبر العباقرة - حياتان فقط داخل المختبر.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['8'],
        lives: 2,
        rewardCoins: 5500,
        rewardGems: 40,
        rewardXp: 2700,
      ),
      _stage(
        campaignId: campaignId,
        order: 76,
        title: 'معركة المختبر',
        subtitle: 'مختبر العباقرة - تفوق على الدكتور كمال.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['8'],
        opponentName: 'الدكتور كمال',
        opponentAccuracy: 85,
        rewardCoins: 5750,
        rewardGems: 42,
        rewardXp: 2825,
      ),
      _stage(
        campaignId: campaignId,
        order: 77,
        title: 'سلسلة التجارب',
        subtitle: 'مختبر العباقرة - اربح السلسلة أمام العالِم نديم.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['8'],
        seriesRounds: 3,
        seriesWinsRequired: 2,
        opponentName: 'العالِم نديم',
        opponentAccuracy: 84,
        rewardCoins: 6000,
        rewardGems: 44,
        rewardXp: 2950,
      ),
      _stage(
        campaignId: campaignId,
        order: 78,
        title: 'فريق المختبر',
        subtitle: 'مختبر العباقرة - تعاون مع نور ضد فريق المختبر.',
        campaignMode: CampaignMode.teamBattle,
        winCondition: CampaignWinCondition.teamScore,
        allowedLevels: const <String>['8'],
        teamAllyName: 'نور',
        teamEnemyName: 'فريق المختبر',
        opponentAccuracy: 84,
        rewardCoins: 6250,
        rewardGems: 46,
        rewardXp: 3075,
      ),
      _stage(
        campaignId: campaignId,
        order: 79,
        title: 'اختبار العباقرة',
        subtitle: 'مختبر العباقرة - سرعة بلا أي مساعدة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['8'],
        timeLimitSeconds: 60,
        allow5050: false,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 6500,
        rewardGems: 48,
        rewardXp: 3200,
      ),
      _stage(
        campaignId: campaignId,
        order: 80,
        title: 'عالم المختبر',
        subtitle: 'مختبر العباقرة - اهزم عالم المختبر.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['8'],
        bossBotName: 'عالم المختبر',
        bossBotIntelligence: 87,
        rewardCoins: 7500,
        rewardGems: 55,
        rewardXp: 3800,
      ),
      _stage(
        campaignId: campaignId,
        order: 81,
        title: 'بوابة الأساطير',
        subtitle: 'بوابة الأساطير - افتح طريق الخبراء.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['3', '8'],
        rewardCoins: 6500,
        rewardGems: 48,
        rewardXp: 3200,
      ),
      _stage(
        campaignId: campaignId,
        order: 82,
        title: 'سباق الأساطير',
        subtitle: 'بوابة الأساطير - سباق دقيقة واحدة.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['3', '8'],
        timeLimitSeconds: 60,
        rewardCoins: 6810,
        rewardGems: 51,
        rewardXp: 3425,
      ),
      _stage(
        campaignId: campaignId,
        order: 83,
        title: 'حياة واحدة أقل',
        subtitle: 'بوابة الأساطير - حياتان فقط للعبور.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['3', '8'],
        lives: 2,
        rewardCoins: 7120,
        rewardGems: 54,
        rewardXp: 3650,
      ),
      _stage(
        campaignId: campaignId,
        order: 84,
        title: 'إقصاء الأساطير',
        subtitle: 'بوابة الأساطير - لا مجال للخطأ.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['3', '8'],
        maxWrongAnswers: 1,
        rewardCoins: 7430,
        rewardGems: 57,
        rewardXp: 3875,
      ),
      _stage(
        campaignId: campaignId,
        order: 85,
        title: 'خصم أسطوري',
        subtitle: 'بوابة الأساطير - واجه الأسطورة.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['3', '8'],
        opponentName: 'الأسطورة',
        opponentAccuracy: 86,
        rewardCoins: 7740,
        rewardGems: 60,
        rewardXp: 4100,
      ),
      _stage(
        campaignId: campaignId,
        order: 86,
        title: 'بلا أي مساعدة',
        subtitle: 'بوابة الأساطير - اعتمد على معرفتك فقط.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['3', '8'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 8050,
        rewardGems: 62,
        rewardXp: 4325,
      ),
      _stage(
        campaignId: campaignId,
        order: 87,
        title: 'سلسلة الأساطير',
        subtitle: 'بوابة الأساطير - اربح أمام حكيم الأساطير.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['3', '8'],
        seriesRounds: 3,
        seriesWinsRequired: 2,
        opponentName: 'حكيم الأساطير',
        opponentAccuracy: 86,
        rewardCoins: 8360,
        rewardGems: 65,
        rewardXp: 4550,
      ),
      _stage(
        campaignId: campaignId,
        order: 88,
        title: 'مطاردة الأسطورة',
        subtitle: 'بوابة الأساطير - اجمع 900 نقطة.',
        campaignMode: CampaignMode.rival,
        winCondition: CampaignWinCondition.beatTargetScore,
        allowedLevels: const <String>['3', '8'],
        targetScore: 900,
        rewardCoins: 8670,
        rewardGems: 68,
        rewardXp: 4775,
      ),
      _stage(
        campaignId: campaignId,
        order: 89,
        title: 'قبل النهاية',
        subtitle: 'بوابة الأساطير - آخر سباق قبل الحارس.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['3', '8'],
        timeLimitSeconds: 55,
        allow5050: true,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 9000,
        rewardGems: 70,
        rewardXp: 5000,
      ),
      _stage(
        campaignId: campaignId,
        order: 90,
        title: 'حارس الأساطير',
        subtitle: 'بوابة الأساطير - اهزم حارس الأساطير.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['3', '8'],
        bossBotName: 'حارس الأساطير',
        bossBotIntelligence: 88,
        rewardCoins: 10000,
        rewardGems: 80,
        rewardXp: 6000,
      ),
      _stage(
        campaignId: campaignId,
        order: 91,
        title: 'مدخل القصر',
        subtitle: 'قصر المليون - بداية الطريق الأخير.',
        campaignMode: CampaignMode.classic,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['3'],
        rewardCoins: 9000,
        rewardGems: 70,
        rewardXp: 5000,
      ),
      _stage(
        campaignId: campaignId,
        order: 92,
        title: 'ممر السرعة',
        subtitle: 'قصر المليون - ممر سريع بخمس وخمسين ثانية.',
        campaignMode: CampaignMode.blitz,
        winCondition: CampaignWinCondition.finishBeforeTime,
        allowedLevels: const <String>['3'],
        timeLimitSeconds: 55,
        rewardCoins: 9625,
        rewardGems: 74,
        rewardXp: 5375,
      ),
      _stage(
        campaignId: campaignId,
        order: 93,
        title: 'ممر الإقصاء',
        subtitle: 'قصر المليون - خطأ واحد يغلق الممر.',
        campaignMode: CampaignMode.elimination,
        winCondition: CampaignWinCondition.noMistakes,
        allowedLevels: const <String>['3'],
        maxWrongAnswers: 1,
        rewardCoins: 10250,
        rewardGems: 78,
        rewardXp: 5750,
      ),
      _stage(
        campaignId: campaignId,
        order: 94,
        title: 'ممر النجاة',
        subtitle: 'قصر المليون - حياتان أمام اختبار القصر.',
        campaignMode: CampaignMode.survival,
        winCondition: CampaignWinCondition.survive,
        allowedLevels: const <String>['3'],
        lives: 2,
        rewardCoins: 10875,
        rewardGems: 82,
        rewardXp: 6125,
      ),
      _stage(
        campaignId: campaignId,
        order: 95,
        title: 'ممر بلا مساعدات',
        subtitle: 'قصر المليون - لا مساعدات في هذا الممر.',
        campaignMode: CampaignMode.noLifeline,
        winCondition: CampaignWinCondition.completeQuestions,
        allowedLevels: const <String>['3'],
        allow5050: false,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 11500,
        rewardGems: 86,
        rewardXp: 6500,
      ),
      _stage(
        campaignId: campaignId,
        order: 96,
        title: 'خصم القصر',
        subtitle: 'قصر المليون - واجه حارس القصر.',
        campaignMode: CampaignMode.battle,
        winCondition: CampaignWinCondition.beatOpponent,
        allowedLevels: const <String>['3'],
        opponentName: 'حارس القصر',
        opponentAccuracy: 87,
        rewardCoins: 12125,
        rewardGems: 90,
        rewardXp: 6875,
      ),
      _stage(
        campaignId: campaignId,
        order: 97,
        title: 'سلسلة النهاية',
        subtitle: 'قصر المليون - اربح ثلاث جولات من خمس.',
        campaignMode: CampaignMode.series,
        winCondition: CampaignWinCondition.winSeries,
        allowedLevels: const <String>['3'],
        seriesRounds: 5,
        seriesWinsRequired: 3,
        opponentName: 'سيد السلسلة',
        opponentAccuracy: 87,
        rewardCoins: 12750,
        rewardGems: 94,
        rewardXp: 7250,
      ),
      _stage(
        campaignId: campaignId,
        order: 98,
        title: 'فريق النهائي',
        subtitle: 'قصر المليون - تعاون مع سارة ضد فريق النهائي.',
        campaignMode: CampaignMode.teamBattle,
        winCondition: CampaignWinCondition.teamScore,
        allowedLevels: const <String>['3'],
        teamAllyName: 'سارة',
        teamEnemyName: 'فريق النهائي',
        opponentAccuracy: 87,
        rewardCoins: 13375,
        rewardGems: 98,
        rewardXp: 7625,
      ),
      _stage(
        campaignId: campaignId,
        order: 99,
        title: 'قبل سيد المليون',
        subtitle: 'قصر المليون - اجمع 950 نقطة قبل المواجهة الأخيرة.',
        campaignMode: CampaignMode.rival,
        winCondition: CampaignWinCondition.beatTargetScore,
        allowedLevels: const <String>['3'],
        targetScore: 950,
        allow5050: true,
        allowAudience: false,
        allowCall: false,
        rewardCoins: 14000,
        rewardGems: 100,
        rewardXp: 8000,
      ),
      _stage(
        campaignId: campaignId,
        order: 100,
        title: 'سيد المليون الأخير',
        subtitle: 'قصر المليون - المواجهة النهائية في طريق المليون.',
        campaignMode: CampaignMode.bossBattle,
        winCondition: CampaignWinCondition.defeatBoss,
        allowedLevels: const <String>['3'],
        timeLimitSeconds: 180,
        bossBotName: 'سيد المليون الأخير',
        bossBotIntelligence: 88,
        rewardCoins: 20000,
        rewardGems: 150,
        rewardXp: 12000,
      ),
    ];
  }

  static List<String> allowedLevelsForOrder(int order) {
    final stage = stages().where((stage) => stage.order == order).firstOrNull;
    return stage?.allowedLevels ?? const <String>['0'];
  }

  static CampaignStage _stage({
    required String campaignId,
    required int order,
    required String title,
    required String subtitle,
    required CampaignMode campaignMode,
    required CampaignWinCondition winCondition,
    required List<String> allowedLevels,
    int timeLimitSeconds = 0,
    bool allow5050 = true,
    bool allowAudience = true,
    bool allowCall = true,
    int? lives,
    int? maxWrongAnswers,
    int? targetScore,
    String? opponentName,
    int? opponentAccuracy,
    int? opponentStartScore,
    String? bossBotName,
    int? bossBotIntelligence,
    int? seriesRounds,
    int? seriesWinsRequired,
    String? teamAllyName,
    String? teamEnemyName,
    int? unlockRequirementStars,
    int? rewardCoins,
    int? rewardGems,
    int? rewardXp,
  }) {
    return CampaignStage(
      id: 'stage_${order.toString().padLeft(3, '0')}',
      campaignId: campaignId,
      order: order,
      title: title,
      subtitle: subtitle,
      type: campaignMode.legacyType,
      campaignMode: campaignMode,
      winCondition: winCondition,
      questionCount: 10,
      timeLimitSeconds: timeLimitSeconds,
      categories: const <String>['general'],
      allowedLevels: allowedLevels,
      minDifficulty: _minDifficultyFor(allowedLevels),
      maxDifficulty: _maxDifficultyFor(allowedLevels),
      unlockRequirementStars:
          unlockRequirementStars ?? (order == 1 ? 0 : (order - 1) * 2),
      allow5050: allow5050,
      allowAudience: allowAudience,
      allowCall: allowCall,
      rewardCoins: rewardCoins ?? 100 + order * 22,
      rewardGems: rewardGems ?? (order % 5 == 0 ? 2 : (order % 3 == 0 ? 1 : 0)),
      rewardXp: rewardXp ?? 70 + order * 18,
      lives: lives,
      maxWrongAnswers: maxWrongAnswers,
      targetScore: targetScore,
      opponentName: opponentName,
      opponentAccuracy: opponentAccuracy,
      opponentStartScore: opponentStartScore,
      bossBotName: bossBotName,
      bossBotIntelligence: bossBotIntelligence,
      seriesRounds: seriesRounds,
      seriesWinsRequired: seriesWinsRequired,
      teamAllyName: teamAllyName,
      teamEnemyName: teamEnemyName,
      starRules: _starRulesFor(campaignMode, timeLimitSeconds),
    );
  }

  static StageStarRules _starRulesFor(
    CampaignMode campaignMode,
    int timeLimitSeconds,
  ) {
    return StageStarRules(
      oneStarMinScore: 0,
      twoStarsMinScore: 0,
      threeStarsMinScore: 0,
      oneStarMinCorrectAnswers: 5,
      twoStarsMinCorrectAnswers: 7,
      threeStarsMinCorrectAnswers: 9,
      maxWrongAnswersForThreeStars: null,
      twoStarsMaxTimeMs:
          campaignMode == CampaignMode.blitz && timeLimitSeconds > 0
              ? timeLimitSeconds * 1000
              : null,
      threeStarsMaxTimeMs:
          campaignMode == CampaignMode.blitz && timeLimitSeconds > 0
              ? timeLimitSeconds * 1000
              : null,
      threeStarsMaxLifelinesUsed: campaignMode == CampaignMode.noLifeline
          ? 0
          : campaignMode == CampaignMode.bossBattle
              ? 1
              : null,
      completedRequired: true,
    );
  }

  static int _minDifficultyFor(List<String> levels) {
    return levels
        .map((level) => int.tryParse(level) ?? 0)
        .reduce((a, b) => a < b ? a : b);
  }

  static int _maxDifficultyFor(List<String> levels) {
    return levels
        .map((level) => int.tryParse(level) ?? 0)
        .reduce((a, b) => a > b ? a : b);
  }
}
